10
[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


[[1.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  1.1 0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  1.2 0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  1.3 0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  1.4 0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  1.5 0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  1.6 0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  1.7 0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  1.8 0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  1.9]]


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [42]:
import numpy as np




[[5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]
 [0. 5. 0. 5. 0.]
 [5. 0. 5. 0. 5.]] 
 0.0
[[5 5 5 5 5]
 [0 5 5 5 5]
 [0 0 5 5 5]
 [0 0 0 5 5]
 [0 0 0 0 5]] 3124.999999999999 

 [[ 0.2 -0.2  0.   0.   0. ]
 [ 0.   0.2 -0.2  0.   0. ]
 [ 0.   0.   0.2 -0.2  0. ]
 [ 0.   0.   0.   0.2 -0.2]
 [ 0.   0.   0.   0.   0.2]]
